

USE ContosoRetailDW

SELECT 
 AVG(UNITPRICE)
FROM DimProduct

--CALCULANDO SUBQUERY COM MEDIA QUE VAI SE ALTERANDO CONFORME ENTRADA DE NOVOS PRODUTOS
SELECT 
PRODUCTKEY,
UNITPRICE
FROM DimProduct
WHERE UnitPrice <= (SELECT AVG(UNITPRICE) FROM DimProduct)
ORDER BY UNITPRICE DESC