
USE ContosoRetailDW

SELECT TOP 100
	S.DATEKEY,
	DATENAME(DAY, S.DateKey) AS DIA,
	DATENAME(WEEKDAY, S.DateKey) AS DIA_DA_SEMANA_DATENAME,
	DATEPART(WEEKDAY, S.DateKey) AS DIA_DA_SEMANA_DATEPART,
	DATENAME(MONTH, S.DateKey) AS MES,
	DATEPART(MONTH, S.DateKey) AS MES
FROM FactOnlineSales AS S
WHERE DATENAME(WEEKDAY, S.DATEKEY) = 'Sexta-Feira'
ORDER BY S.DateKey DESC