
USE ContosoRetailDW

-- DATEDIFF (INTERVALO, DATA_INICIO, DATA_FINAL)

SELECT DATEDIFF(DAY,'2023-07-10',GETDATE()) AS DIA
SELECT DATEDIFF(MONTH,'2023-06-10',GETDATE()) AS MES
SELECT DATEDIFF(YEAR,'2002-06-10',GETDATE()) AS ANO

SELECT DISTINCT TOP 100
	S.DateKey, 
	GETDATE() AS DATA_DE_HOJE,
	DATEDIFF(DAY,S.DateKey, GETDATE()) AS DIFERENCA
FROM FactOnlineSales AS S
ORDER BY 1 DESC