
SELECT 
'SQL ษ MAIS LEGAL QUE POWER BI',
SUBSTRING('SQL ษ MAIS LEGAL QUE POWER BI', 1, 3) AS SUB1,
SUBSTRING('SQL ษ MAIS LEGAL QUE POWER BI', 22, 9) AS SUB2,
RIGHT('SQL ษ MAIS LEGAL QUE POWER BI', 8) AS 'RIGHT',
LEFT('SQL ษ MAIS LEGAL QUE POWER BI', 3) AS 'LEFT',
LEFT(RIGHT('SQL ษ MAIS LEGAL QUE POWER BI', 8), 5) AS 'LEFT RIGHT',
CHARINDEX('MAIS', 'SQL ษ MAIS LEGAL QUE POWER BI') AS 'CHARINDEX', -- MOSTRA A POSIวรO ONDE A PALAVRA ESPECIFICADA ษ MOSTRADA
LEN('SQL ษ MAIS LEGAL QUE POWER BI') AS 'LEN',
RIGHT('SQL ษ MAIS LEGAL QUE POWER BI', LEN('SQL ษ MAIS LEGAL QUE POWER BI')-CHARINDEX('MAIS','SQL ษ MAIS LEGAL QUE POWER BI')+1) --EXTRAI A PARTIR DE UM TEXTO PARA FRENTE, NESSE CASO A PARTIR DO MAIS