
USE ContosoRetailDW

--- SUBQUERY / SUB CONSULTA

SELECT
	AVG(SQ.VENDAS)
FROM(
	SELECT
	DATEPART(YEAR, S.DATEKEY) AS ANO,
	DATEPART(MONTH, S.DATEKEY) AS MES,
	SUM(S.SALESAMOUNT) AS VENDAS
	FROM FACTSALES AS S
	GROUP BY DATEPART(YEAR, S.DATEKEY), DATEPART(MONTH, S.DATEKEY)
)	AS SQ

-- CTE - COMMON TABLE EXPRESSION

WITH SALES_MONTH_AVG (ANO, MES, VENDAS)
AS
(
	SELECT
	DATEPART(YEAR, S.DATEKEY) AS ANO,
	DATEPART(MONTH, S.DATEKEY) AS MES,
	SUM(S.SALESAMOUNT) AS VENDAS
	FROM FACTSALES AS S
	GROUP BY DATEPART(YEAR, S.DATEKEY), DATEPART(MONTH, S.DATEKEY)
)
SELECT
	AVG(SALES_MONTH_AVG.VENDAS) MEDIA_MENSAL
FROM SALES_MONTH_AVG
