USE ContosoRetailDW

;WITH ANALISE_PRODUTO(ANO, MES, ID_PRODUTO, NOME_PRODUTO, QTDE)
AS(
	SELECT
	DATEPART(YEAR, S.DateKey) AS ANO,
	DATEPART(MONTH, S.DATEKEY) AS MES,
	S.PRODUCTKEY AS ID_PRODUTO,
	P.PRODUCTNAME AS NOME_PRODUTO,
	SUM(S.SALESQUANTITY) AS QTDE
	FROM FactSales AS S
	INNER JOIN DimProduct AS P ON P.ProductKey = S.ProductKey
	GROUP BY DATEPART(YEAR, S.DateKey),
	DATEPART(MONTH, S.DATEKEY), S.ProductKey, P.ProductName
	)

SELECT TOP 10
	A.*,
	P.*
FROM ANALISE_PRODUTO AS A
INNER JOIN DimProduct AS P ON P.ProductKey = A.ID_PRODUTO
ORDER BY QTDE DESC