-- SELECIONAR CLIENTES DISTINTOS DA BASE ADVENTUREWORKS

USE AdventureWorksDW2022

SELECT DISTINCT
CustomerKey
FROM FactInternetSales

-- USANDO SUBQUERY

SELECT COUNT(*) AS TOTAL_CLIENTES_DISTINTOS
FROM (
	SELECT CustomerKey
	FROM FactInternetSales
	GROUP BY CustomerKey
) AS DISTINTOS_CLIENTES

-- USANDO CTE

;WITH CLIENTES_DISTINTOS AS (
	SELECT 
	CUSTOMERKEY,
	ROW_NUMBER() OVER(PARTITION BY CUSTOMERKEY ORDER BY CUSTOMERKEY) AS 'ROWNUMBER'
	FROM FactInternetSales
)
SELECT
COUNT(*)
FROM CLIENTES_DISTINTOS
WHERE ROWNUMBER = 1

