
-- MUDA O FORMATO DE DATA QUE ESTOU USANDO NO SCRIPT PARA TRAZER OS VALORES DO BANCO DE DADOS.

SET DATEFORMAT YMD
USE ContosoRetailDW

SELECT DISTINCT 
	S.DateKey
FROM FactOnlineSales AS S
WHERE S.DateKey BETWEEN '2007-12-01' AND '2007-12-31'
