
USE ContosoRetailDW

SELECT GETDATE () AS DATA_ATUAL

SELECT GETDATE ()+10 AS DATA_ATUAL_10

SELECT YEAR(GETDATE()) AS ANO
SELECT MONTH(GETDATE()) AS MES
SELECT DAY(GETDATE()) AS DIA

SELECT
*
FROM FactOnlineSales
WHERE YEAR(DATEKEY) = 2007 AND MONTH(DATEKEY) = 12 AND DAY(DATEKEY) = 31
