
USE ContosoRetailDW


SELECT TOP 100
	S.DATEKEY,
	DATEPART(YEAR, S.DateKey) AS ANO,
	DATEPART(MONTH, S.DateKey) AS MES,
	DATEPART(DAY, S.DateKey) AS DIA,
	DATEPART(DAYOFYEAR, S.DateKey) AS DIA_DO_ANO,
	DATEPART(WEEKDAY, S.DateKey) AS DIA_DA_SEMANA

FROM FactOnlineSales AS S
ORDER BY S.DateKey DESC

SELECT DATEPART(WEEKDAY, GETDATE()+2) AS DIA_DA_SEMANA

SELECT TOP 100 *
FROM FactOnlineSales
WHERE DATEPART(DAY, DateKey) = 31 AND 
DATEPART(MONTH, DateKey) = 12 AND
DATEPART(YEAR, DateKey) = 2009
