
USE ContosoRetailDW

--DATEADD(INTERVALO, QUANTIDADE, DATA)
SELECT
	GETDATE() AS HOJE,
	DATEADD(DAY,10,GETDATE()) AS DIA,
	DATEADD(MONTH, 1, GETDATE()) AS UM_MES,
	DATEADD(MONTH, -12, GETDATE()) AS MENOS_DOZE_MES,
	DATEADD(YEAR, 1, GETDATE()) AS UM_ANO,
	DATEADD(HOUR, 1, GETDATE()) AS UMA_HORA
