
USE ContosoRetailDW

-- END OF MONTH
SELECT EOMONTH(GETDATE())

--ADICIONANDO 01 MES

SELECT 
	GETDATE(),
	EOMONTH(GETDATE()), -- END OF MONTH
	EOMONTH(GETDATE(), 1), -- ADICIONANDO UM MES
	EOMONTH(GETDATE(), -1) -- SUBTRAINDO UM MES
