
SELECT 
'SQL É MAIS LEGAL QUE POWER BI',
SUBSTRING('SQL É MAIS LEGAL QUE POWER BI', 1, 3) AS SUB1,
SUBSTRING('SQL É MAIS LEGAL QUE POWER BI', 22, 9) AS SUB2,
RIGHT('SQL É MAIS LEGAL QUE POWER BI', 8) AS 'RIGHT',
LEFT('SQL É MAIS LEGAL QUE POWER BI', 3) AS 'LEFT',
LEFT(RIGHT('SQL É MAIS LEGAL QUE POWER BI', 8), 5) AS 'LEFT RIGHT',
CHARINDEX('MAIS', 'SQL É MAIS LEGAL QUE POWER BI') AS 'CHARINDEX', -- MOSTRA A POSIÇÃO ONDE A PALAVRA ESPECIFICADA É MOSTRADA
LEN('SQL É MAIS LEGAL QUE POWER BI') AS 'LEN',
RIGHT('SQL É MAIS LEGAL QUE POWER BI', LEN('SQL É MAIS LEGAL QUE POWER BI')-CHARINDEX('MAIS','SQL É MAIS LEGAL QUE POWER BI')+1) --EXTRAI A PARTIR DE UM TEXTO PARA FRENTE, NESSE CASO A PARTIR DO MAIS
