USE ContosoRetailDW;

WITH TOTAL_VENDAS(ANO, MES, VENDAS) AS
(
	SELECT	
	DATEPART(YEAR, S.DATEKEY) AS ANO,
	DATEPART(MONTH, S.DATEKEY) AS MES,
	SUM(S.SALESAMOUNT) AS VENDAS
	FROM FACTONLINESALES S
	GROUP BY DATEPART(YEAR, S.DATEKEY), DATEPART(MONTH, S.DATEKEY)
)
SELECT
	ANO, MES,
	FORMAT(VENDAS, 'C0') AS 'VENDAS',
	FORMAT(SUM(VENDAS) OVER(PARTITION BY ANO ORDER BY ANO, MES ASC
	                  ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), 'C0') AS VENDAS_YTD,
	FORMAT(AVG(VENDAS) OVER(PARTITION BY ANO ORDER BY ANO, MES ASC
	                  ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), 'C0') AS VENDAS_AVG,
	FORMAT(AVG(VENDAS) OVER(ORDER BY ANO, MES ASC
	                  ROWS BETWEEN 3 PRECEDING AND 1 PRECEDING), 'C0') AS VENDAS_AVG_3M,
	FORMAT(SUM(VENDAS) OVER(ORDER BY ANO, MES ASC
	                  ROWS BETWEEN 1 PRECEDING AND 1 PRECEDING), 'C0') AS VENDAS_ULTIMO_MES
FROM TOTAL_VENDAS
ORDER BY ANO,MES
