USE ContosoRetailDW;

WITH TOTAL_VENDAS(ANO, MES, VENDAS) AS
(
	SELECT	
	DATEPART(YEAR, S.DATEKEY) AS ANO,
	DATEPART(MONTH, S.DATEKEY) AS MES,
	SUM(S.SALESAMOUNT) AS VENDAS
	FROM FACTONLINESALES S
	GROUP BY DATEPART(YEAR, S.DATEKEY), DATEPART(MONTH, S.DATEKEY)
)
SELECT
	ANO, MES,
	FORMAT(VENDAS, 'C0') AS 'VENDAS',
	FORMAT(LAG(VENDAS, 1,0) OVER(ORDER BY ANO, MES ASC), 'C0') AS MES_ANTERIOR,
	FORMAT(LEAD(VENDAS, 1,0) OVER(ORDER BY ANO, MES ASC), 'C0') AS MES_POSTERIOR
FROM TOTAL_VENDAS
ORDER BY ANO,MES

USE BikeStores;
SELECT
	C.CUSTOMERID,
	C.LASTNAME,
	C.FIRSTNAME,
	O.ORDERID,
	LAG(O.ORDERID, 1, O.ORDERID) OVER(PARTITION BY C.CUSTOMERID ORDER BY O.ORDERID ASC) ULTIMAORDER,
	LEAD(O.ORDERID) OVER(PARTITION BY C.CUSTOMERID ORDER BY O.ORDERID ASC) PROXIMAORDER
FROM SALES.CUSTOMER AS C
INNER JOIN SALES.[ORDER] O ON C.CUSTOMERID = O.CUSTOMERID
ORDER BY C.CUSTOMERID
