
USE AdventureWorksDW2022

-- TOTAL DE VENDAS
SELECT
FORMAT(SUM(SALESAMOUNT),'C0') AS TOTAL_DE_VENDAS
FROM FactInternetSales

-- MEDIA DE VENDAS
SELECT
FORMAT(AVG(SALESAMOUNT),'C0') AS MEDIA_DE_VENDAS
FROM FactInternetSales
